 const Colors = [
      //  'AntiqueWhite' ,	
       'Aqua' 	,
        'Aquamarine' ,
        'Azure' ,
        'Beige' ,
        'Bisque' ,
        'Black' 	,
        'BlanchedAlmond', 
        'Blue' ,
        'BlueViolet', 
        'Brown' 	,
        'BurlyWood', 
        'CadetBlue' ,
        'Chartreuse' ,
        'Chocolate' ,
        'Coral' 	,
        'CornflowerBlue', 	
        'Cornsilk' ,
        'Crimson' ,	
        'Cyan' 	,
        'DarkBlue' ,	
        'DarkCyan' ,
        'DarkGoldenRod' ,
        'DarkGray' ,
        'DarkGreen' ,
        'DarkKhaki' ,
        'DarkMagenta' 	,
        'DarkOliveGreen' 	,
        'Darkorange' ,
        'DarkOrchid' 	,	 
        'DarkRed' 	,
        'DarkSalmon' ,
        'DarkSeaGreen', 	
        'DarkSlateBlue' ,
        'DarkSlateGrey' ,	 
        'DarkTurquoise' 	 ,
        'DarkViolet' 	 ,
        'DeepPink' 	 ,
        'DeepSkyBlue' ,	
        'DimGrey' 	,	 
        'DodgerBlue' 	 ,
        'FireBrick' 	 ,
       // 'FloralWhite' ,	
        'ForestGreen' ,	 
        'Fuchsia' ,
        'Gainsboro', 	
      //  'GhostWhite' ,
        'Gold' 	,
        'GoldenRod' ,	
        'Gray' ,
        'Green' ,
        'GreenYellow', 	
        'HoneyDew' 	,
        'HotPink' 	,
        'IndianRed'  ,
        'Indigo' 	,
        'Ivory' ,
        'Khaki' ,
        'Lavender', 	
        'LavenderBlush', 	
        'LawnGreen', 
        'LemonChiffon', 	
        'LightBlue' ,
        'LightCoral' ,	
        'LightCyan' 	,
        'LightGoldenRodYellow', 	 
        'LightGray' ,
        'LightGreen' 	,
        'LightPink' 	,
        'LightSalmon' ,	 
        'LightSeaGreen', 	
        'LightSkyBlue' ,	 
        'LightSlateGrey' ,	
        'LightSteelBlue' ,
        'LightYellow' 	, 
        'Lime' 	,
        'LimeGreen', 	
        'Linen' ,
        'Magenta', 	
        'Maroon' 	,
        'MediumAquaMarine', 
    ]

const MyColorsamt = function () {
    return Colors.length
}
const MyColors = function (num) {
    return Colors[num]
}
export default MyColors
export  {MyColorsamt};